[package]
name = "hhat_lang"
version = "0.3.0-alpha.1"
edition = "2024"

[dependencies]
peg = "0.8.5"
walkdir = "2.5.0"
itertools = "0.14.0"
cranelift = "0.128.3"
cranelift-module = "0.128.3"
cranelift-jit = "0.128.3"
thin-vec = "0.2.14"
